# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  # pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-66026d0d-c56b-42b4-b103-ed24f32152ed";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-66026d0d-c56b-42b4-b103-ed24f32152ed".device = "/dev/disk/by-uuid/66026d0d-c56b-42b4-b103-ed24f32152ed";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0000-7DDC";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-f0e76fce-ba6b-4eb1-8376-e42f2635f5a8";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
